[project]
name = "VSLAM-LAB"
version = "0.1.0"
description = "VSLAM-LAB"
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["linux-64"]

[tasks]
vslamlab = {cmd = "pixi run -e vslamlab python vslamlab_run.py $ARGUMENT $OVEWRITE && pixi run -e vslamlab python vslamlab_eval.py $ARGUMENT $OVEWRITE", env = {ARGUMENT = "--exp_yaml exp_mono.yaml", OVEWRITE = "-overwrite"}}
vslamlab_debug = {cmd = "pixi run -e vslamlab python vslamlab_run.py $ARGUMENT $OVEWRITE && pixi run -e vslamlab python vslamlab_eval.py $ARGUMENT $OVEWRITE", env = {ARGUMENT = "--exp_yaml exp_debug.yaml", OVEWRITE = " "}}
evaluate = {cmd = "pixi run -e vslamlab python vslamlab_eval.py $ARGUMENT $OVEWRITE", env = {ARGUMENT = "--exp_yaml exp_debug.yaml", OVEWRITE = " "}}

set-benchmark-path  = {cmd = "pixi run -e vslamlab python path_constants.py set_VSLAMLAB_BENCHMARK_path"}
set-evaluation-path = {cmd = "pixi run -e vslamlab python path_constants.py set_VSLAMLAB_EVALUATION_path"}
demo = {cmd = "pixi run --frozen -e vslamlab python vslamlab_demo.py"}
baseline-info = {cmd = "pixi run --frozen -e vslamlab python vslamlab_utilities.py baseline_info"}
sequence-info = {cmd = "pixi run --frozen -e vslamlab python vslamlab_utilities.py sequence_info"}
print_datasets = {cmd = "pixi run --frozen -e vslamlab python vslamlab_utilities.py print_datasets"}
print_baselines = {cmd = "pixi run --frozen -e vslamlab python vslamlab_utilities.py print_baselines"}
get-benchmark-path = {cmd = "VSLAMLAB_BENCHMARK=$(python3 -c 'from path_constants import VSLAMLAB_BENCHMARK; print(VSLAMLAB_BENCHMARK)')"}
clean_swap = {cmd = "sudo /sbin/swapoff -a && sudo /sbin/swapon -a"}
kill_all = {cmd = "pkill -f -e 'droidslam|mast3rslam|dpvo|monogs|orbslam2|colmap|glomap|gensfm|mast3r|vggt|dvsevo|vslamlab' && sudo /sbin/swapoff -a && sudo /sbin/swapon -a"} 

# environments begin
[environments]
vslamlab = {features = ["vslamlab"], no-default-feature = true}
cuda126 = {features = ["cuda126"], no-default-feature = true, solve-group = "cuda126"}
py10 = {features = ["py10"], no-default-feature = true, solve-group = "py10"}
py11 = {features = ["py11"], no-default-feature = true, solve-group = "py11"}
x11 = {features = ["x11"], no-default-feature = true, solve-group = "x11"}
opengl = {features = ["opengl"], no-default-feature = true, solve-group = "opengl"}

droidslam = {features = ["droidslam"], no-default-feature = true}
droidslam-dev = {features = ["droidslam-dev", "cuda126", "py11"], no-default-feature = true, solve-group = "cuda126py11"}
dvsevo-dev = {features = ["dvsevo-dev", "x11", "opengl"], no-default-feature = true}
cmaxslam-dev = {features = ["cmaxslam-dev"], no-default-feature = true}

# environments end

# VSLAM-LAB
[feature.vslamlab]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["linux-64"]

[feature.vslamlab.dependencies]
python="*"
pyyaml="*"
matplotlib="*"
pandas="*"
py-opencv="*"
scipy="*"
requests="*"
inputimeout="*"
scikit-learn="*"
tqdm="*"
google-api-python-client="*"
google-auth-oauthlib="*"
huggingface_hub="*"
py7zr="*"
exifread="*"
pyproj="*"
nvidia-ml-py="*"
evo = "*"
git-lfs = "*"
piexif = "*"
#git = "*"

########################################################################################################################
########################################################################################################################
# droidslam begin
[feature.droidslam]
channels = ["https://fast.prefix.dev/conda-forge", "fontan"]
platforms = ["linux-64"]

[feature.droidslam.system-requirements]
cuda = "12.0"

[feature.droidslam.tasks]
git-clone = {cmd = 'git clone https://huggingface.co/vslamlab/droidslam Baselines/DROID-SLAM'}
execute_mono = {cmd = 'vslamlab_droidslam_mono'}

[feature.droidslam.dependencies]
droidslam="*"
lietorch = {version = "*", channel = "fontan"}  
open3d = ">=0.18.0,<0.19"
# droidslam end

########################################################################################################################
########################################################################################################################
################################################ DEVELOPMENT PACKAGES ##################################################
########################################################################################################################
########################################################################################################################

# ########################################################################################################################
# ########################################################################################################################
# cuda126 begin
[feature.cuda126]
platforms = ["linux-64"]
channels = ["https://fast.prefix.dev/conda-forge"]

[feature.cuda126.system-requirements]
cuda = "12.0"

[feature.cuda126.dependencies]
# CUDA Build Tools
cuda-compiler = "*"
cuda-version = "12.6.*"
cuda-cudart-dev = "*"
cuda-crt = "*"
libcusparse-dev = "*"
cuda-driver-dev = "*"
cuda-nvcc = "*"
cuda-nvrtc-dev = "*"
cuda-nvtx = "*"
cuda-nvtx-dev = "*"
cuda-nvml-dev = "*"
cuda-profiler-api = "*"

# CUDA Libraries
cudnn = "*"
libcublas-dev = "*"
libcudss-dev = "*"
libcufile-dev = "*"
libcufft-dev = "*"
libcurand-dev = "*"
libcusolver-dev = "*"
cusparselt = "*"
libnvjitlink = "*"
# cuda126 end

# ########################################################################################################################
# py10 begin
[feature.py10]
platforms = ["linux-64"]
channels = ["https://fast.prefix.dev/conda-forge"]

[feature.py10.dependencies]
python="3.10.*"
setuptools = "*"
pip = "*"
# py10 end

# ########################################################################################################################
# py11 begin
[feature.py11]
platforms = ["linux-64"]
channels = ["https://fast.prefix.dev/conda-forge"]

[feature.py11.dependencies]
python="3.11.*"
setuptools = "*"
pip = "*"
# py11 end

# ########################################################################################################################
# x11 begin
[feature.x11]
platforms = ["linux-64"]
channels = ["https://fast.prefix.dev/conda-forge"]

[feature.x11.dependencies]
xorg-libxext = "*"
xorg-libx11 = "*"
xorg-libxfixes = "*"
xorg-libxrender = "*"
xorg-libice = "*"
xorg-libsm = "*"
xorg-libxdmcp = "*"
xorg-libxau = "*"
xorg-xorgproto = "*"
libxkbcommon = "*"
# x11 end

# ########################################################################################################################
# opengl begin
[feature.opengl]
platforms = ["linux-64"]
channels = ["https://fast.prefix.dev/conda-forge"]

[feature.opengl.dependencies]
libgl-devel = "*"
libegl-devel = "*"
libglvnd-devel = "*"
libopengl-devel = "*"
# opengl end

########################################################################################################################
########################################################################################################################
# droidslam-dev begin
[feature.droidslam-dev]
channels = ["https://fast.prefix.dev/conda-forge", "fontan"]
platforms = ["linux-64"]

[feature.droidslam-dev.system-requirements]
cuda = "12.0"

[feature.droidslam-dev.tasks]
git-clone = {cmd = "git-clone.sh VSLAM-LAB DROID-SLAM DROID-SLAM-DEV"}
install = {cmd = "python setup.py install", cwd = "Baselines/DROID-SLAM-DEV"}
execute_mono = {cmd = 'python vslamlab_droidslam_mono.py',  cwd = 'Baselines/DROID-SLAM-DEV'}

[feature.droidslam-dev.dependencies]
# Build Tools
compilers="*"
cmake = "*"
make="*"

# Specialized Libraries
lietorch = {version = "*", channel = "fontan"}  

# Core Libraries
pytorch-gpu = "*"
opencv = "*"
torch-scatter ="*"

# Logging, Evaluation & Visualization
open3d = ">=0.18.0,<0.19"
scipy = ">=1.14.1,<2"
suitesparse = ">=7.8.2,<8"
matplotlib = ">=3.9.2,<4"
pyyaml = ">=6.0.2,<7"
huggingface_hub="*"
tqdm = "*"
# droidslam-dev end

########################################################################################################################
########################################################################################################################
# dvsevo-dev begin
[feature.dvsevo-dev]
channels = ["conda-forge", "robostack-noetic"]
platforms = ["linux-64"]

[feature.dvsevo-dev.system-requirements]
cuda = "12.0"

[feature.dvsevo-dev.tasks]
mkdir_dvsevo = {cmd = "mkdir -p Baselines/DVSEVO-DEV/catkin_ws/src"}
get_repo = {cmd = "git-clone.sh alejandrofontan rpg_dvs_evo_open DVSEVO-DEV/catkin_ws/src/rpg_dvs_evo_open", depends-on = ['mkdir_dvsevo']}
git-clone = {cmd = 'chmod +x rpg_dvs_evo_open/install.sh && ./rpg_dvs_evo_open/install.sh noetic', cwd = "Baselines/DVSEVO-DEV/catkin_ws/src", depends-on = ['get_repo']} 
catkin_config = {cmd = "catkin config --init --mkdirs --merge-devel --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED=ON", cwd = "Baselines/DVSEVO-DEV/catkin_ws"}
install = {cmd = "catkin build dvs_tracking --cmake-args -DCMAKE_CXX_STANDARD=14", cwd = "Baselines/DVSEVO-DEV/catkin_ws", depends-on = ['catkin_config']}  
execute_mono.cmd = "bash -c 'source ../devel/setup.bash && export QT_QPA_PLATFORM_PLUGIN_PATH=$CONDA_PREFIX/lib/qt5/plugins/platforms  && roslaunch dvs_tracking {{ LAUNCH_FILE }} auto_trigger:=true'"
execute_mono.cwd = "Baselines/DVSEVO-DEV/catkin_ws/src" 
execute_mono.args = ["LAUNCH_FILE"] 

[feature.dvsevo-dev.dependencies]
python = "*"
pytorch = "*"
torchvision = "*"
pyyaml = "*"
requests = "*"
tqdm = "*"
scipy = "*"
numpy = ">=1.26.2,<2"
h5py = "*"
matplotlib = "*"
pynmea2 = "*"
pandas = "*"
numba = "*"
tonic = "*"
prettytable = "*"

# Build Tools
compilers="*"
cmake = "<4"
make="*"

# ROS Libraries
ros-noetic-desktop-full = "*"
ros-noetic-sophus = "*"
ros-noetic-pcl-ros = "*"
ros-noetic-eigen-conversions = "*"
ros-noetic-camera-info-manager = "*"
ros-noetic-image-view = "*"
ros-noetic-image-geometry = "*"
ros-noetic-vision-msgs = "*"
ros-noetic-rosbag = "*"
ros-noetic-cv-bridge = "*"

vcstool = "*"
fftw = "*"           
glew = "*"           
opencv = "*"         
yaml-cpp = "*"      
catkin_tools = "*"
glog = "0.5.*"
gflags = "*"
libcaer = "*"
libstdcxx-ng = "*"
libgcc-ng = "*"
vtk="*"
qt-main = "*"
# dvsevo-dev end

########################################################################################################################
########################################################################################################################
# cmaxslam-dev begin
[feature.cmaxslam-dev]
channels = ["conda-forge", "robostack-noetic"]
platforms = ["linux-64"]

# [feature.cmaxslam-dev.system-requirements]
# cuda = "12.0"

[feature.cmaxslam-dev.tasks]
mkdir_cmaxslam = {cmd = "mkdir -p Baselines/CMAXSLAM-DEV/catkin_ws/src"}
git-clone = {cmd = "git-clone.sh alejandrofontan cmax_slam CMAXSLAM-DEV/catkin_ws/src/cmax_slam", depends-on = ['mkdir_cmaxslam']}
#git-clone = {cmd = 'chmod +x rpg_dvs_evo_open/install.sh && ./rpg_dvs_evo_open/install.sh noetic', cwd = "Baselines/DVSEVO-DEV/catkin_ws/src", depends-on = ['get_repo']} 
catkin_config = {cmd = "catkin config --init --mkdirs --merge-devel --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_STANDARD=14", cwd = "Baselines/CMAXSLAM-DEV/catkin_ws"}
vcs-import = {cmd = "vcs-import < cmax_slam/dependencies.yaml", cwd = "Baselines/CMAXSLAM-DEV/catkin_ws/src"}


install = {cmd = "catkin build cmax_slam --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_STANDARD=14", cwd = "Baselines/CMAXSLAM-DEV/catkin_ws", depends-on = ['catkin_config']}  
# execute_mono.cmd = "bash -c 'source ../devel/setup.bash && export QT_QPA_PLATFORM_PLUGIN_PATH=$CONDA_PREFIX/lib/qt5/plugins/platforms  && roslaunch dvs_tracking {{ LAUNCH_FILE }} auto_trigger:=true'"
# execute_mono.cwd = "Baselines/DVSEVO-DEV/catkin_ws/src" 
# execute_mono.args = ["LAUNCH_FILE"] 

[feature.cmaxslam-dev.dependencies]
# python = "*"
# pytorch = "*"
# torchvision = "*"
# pyyaml = "*"
# requests = "*"
# tqdm = "*"
# scipy = "*"
# numpy = ">=1.26.2,<2"
# h5py = "*"
# matplotlib = "*"
# pynmea2 = "*"
# pandas = "*"
# numba = "*"
# tonic = "*"
# prettytable = "*"

# # Build Tools
compilers="*"
cmake = "*"
make="*"

# # ROS Libraries
ros-noetic-desktop-full = "*"
ros-noetic-sophus = "*"
ros-noetic-pcl-ros = "*"
ros-noetic-eigen-conversions = "*"
ros-noetic-camera-info-manager = "*"
ros-noetic-image-view = "*"
ros-noetic-image-geometry = "*"
ros-noetic-vision-msgs = "*"
ros-noetic-rosbag = "*"
ros-noetic-cv-bridge = "*"
catkin_tools = "*"

vcstool = "*"

# fftw = "*"           
# glew = "*"           
# opencv = "*"         
# yaml-cpp = "*"      
glog = "*"
gflags = "*"
gsl = "*"
# libcaer = "*"
# libstdcxx-ng = "*"
# libgcc-ng = "*"
# vtk="*"
# qt-main = "*"

# cmaxslam-dev end